### ISSUE TITLE
Single js file for use in browser

### ISSUE THREAD

**Issue by ammsa** [lpimem/rangeblock#3]
I would like to use this but it's in typescript. Is there a compiled JS version for use in browser (without SystemJS).?

**Comment by lpimem** [comment]
Thanks for your interest in the project. 
Unfortunately there is currently no single js version available. But you can use 3rd party tools to generate a single js file by yourself. I haven't kept up with the front-end part for sometime, but back to the days it was created, the webpack tool can do that easily. Here is an example of using webpack to output a single js for my other project: https://github.com/lpimem/hlc/blob/master/webpack.config.js
